<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
		<PublishAot>true</PublishAot>
		<IsAotCompatible>true</IsAotCompatible>
		<stripSymbols>false</stripSymbols>
		<PlatformTarget>x86</PlatformTarget>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<InvariantGlobalization>true</InvariantGlobalization>
		<AssemblyVersion>0.0.0.4</AssemblyVersion>
		<FileVersion>0.0.0.4</FileVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Misc\Eris.BeonSerializer\Eris.BeonSerializer.csproj" />
      <ProjectReference Include="..\Native\Eris.YRSharp\Eris.YRSharp.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Include="..\publish.cmd" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="ZLinq" Version="1.5.4" />
    </ItemGroup>

</Project>
